language: python
python:
  - "3.5"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
script: python -m unittest discover -t . -s ni/test/
after_success:
  - codecov
